In [109]:
import pandas as pd 

df = pd.read_csv('spam.csv')
df.head()

Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [110]:
pip install nltk

Note: you may need to restart the kernel to use updated packages.


In [111]:
import nltk

from nltk.tokenize import word_tokenize

from nltk.corpus import stopwords

from nltk.stem import PorterStemmer

nltk.download('punkt')

nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [112]:
text="Hi: I am working on building a model to classify: spam or not spam"

tokens = word_tokenize(text.lower())
tokens

['hi',
 ':',
 'i',
 'am',
 'working',
 'on',
 'building',
 'a',
 'model',
 'to',
 'classify',
 ':',
 'spam',
 'or',
 'not',
 'spam']

In [113]:
import string

tokens = [token for token in tokens if token not in string.punctuation]
tokens

['hi',
 'i',
 'am',
 'working',
 'on',
 'building',
 'a',
 'model',
 'to',
 'classify',
 'spam',
 'or',
 'not',
 'spam']

In [114]:
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [115]:
stop_words = stopwords.words('english')

tokens = [token for token in tokens if token not in stop_words]
tokens

['hi', 'working', 'building', 'model', 'classify', 'spam', 'spam']

In [116]:
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [117]:
print(len(stop_words))

179


In [118]:
stemmer = PorterStemmer()

tokens = [stemmer.stem(token) for token in tokens]
tokens

['hi', 'work', 'build', 'model', 'classifi', 'spam', 'spam']

In [119]:
ps = PorterStemmer()

print(ps.stem("build"))
print(ps.stem("building"))
print(ps.stem("buildings"))
print(ps.stem("built"))
print(ps.stem("builder"))

build
build
build
built
builder


In [120]:
import re

def preprocess_text(text):
    
    tokens = word_tokenize(text.lower())
    
    tokens = [token for token in tokens if token not in string.punctuation]
    
    stop_words = stopwords.words('english')
    tokens = [token for token in tokens if token not in stop_words]
    
    stemmer = PorterStemmer()
    tokens = [stemmer.stem(token) for token in tokens]
    
    preprocessed_text = ' '.join(tokens)

    preprocessed_text = re.sub(r'http\S+|www\S+', '', preprocessed_text)

    preprocessed_text = re.sub(r'\d+', '', preprocessed_text)
    return preprocessed_text

In [121]:
email = "As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune"

preprocessed_email = preprocess_text(email)
print(preprocessed_email)

per request 'mell mell oru minnaminungint nurungu vettam set callertun caller press  copi friend callertun


In [122]:
df['processed_Message'] = df['Message'].apply(preprocess_text)

df

Category                                            Message  \
0            0  Go until jurong point, crazy.. Available only ...   
1            0                      Ok lar... Joking wif u oni...   
2            1  Free entry in 2 a wkly comp to win FA Cup fina...   
3            0  U dun say so early hor... U c already then say...   
4            0  Nah I don't think he goes to usf, he lives aro...   
...        ...                                                ...   
5567         1  This is the 2nd time we have tried 2 contact u...   
5568         0               Will ü b going to esplanade fr home?   
5569         0  Pity, * was in mood for that. So...any other s...   
5570         0  The guy did some bitching but I acted like i'd...   
5571         0                         Rofl. Its true to its name   

                                      processed_Message  
0     go jurong point crazi .. avail bugi n great wo...  
1                         ok lar ... joke wif u oni ...  
2     free entri  wkli comp win fa cup final tkt st ...  
3           u dun say earli hor ... u c alreadi say ...  
4              nah n't think goe usf live around though  
...                                                 ...  
5567  nd time tri  contact u. u £ pound prize  claim...  
5568                            ü b go esplanad fr home  
5569                              piti mood ... suggest  
5570  guy bitch act like 'd interest buy someth els ...  
5571                                     rofl true name  

[5572 rows x 3 columns]

In [123]:
df_spam = df[df['Category']=='0']

In [124]:
pip install wordcloud

Note: you may need to restart the kernel to use updated packages.


In [125]:
print(df_spam['processed_Message'].unique()) 

[]


In [126]:
print(f"Total words in WordCloud: {len(spam_words_str.split())}")

Total words in WordCloud: 0


In [128]:
from sklearn.feature_extraction.text import CountVectorizer 

documents = [
    "My cat and dog sat on the mat",
    "strange cat jumped over the mat",
    "His cat ate the mouse ran across the mat",
    "Her dog run after my cat and mouse",
]

max_features=6

count_vectorizer = CountVectorizer(max_features=max_features)

vectors = count_vectorizer.fit_transform(documents)

print(vectors)

  (0, 4)	1
  (0, 0)	1
  (0, 1)	1
  (0, 5)	1
  (0, 2)	1
  (1, 0)	1
  (1, 5)	1
  (1, 2)	1
  (2, 0)	1
  (2, 5)	2
  (2, 2)	1
  (2, 3)	1
  (3, 4)	1
  (3, 0)	1
  (3, 1)	1
  (3, 3)	1


In [129]:
feature_names = count_vectorizer.get_feature_names_out()

print("Feature Names:")
print(feature_names)

Feature Names:
['cat' 'dog' 'mat' 'mouse' 'my' 'the']


In [130]:
print(vectors.toarray())

[[1 1 1 0 1 1]
 [1 0 1 0 0 1]
 [1 0 1 1 0 2]
 [1 1 0 1 1 0]]


In [131]:
example_df = pd.DataFrame(data=vectors.toarray(),columns=feature_names)

example_df

cat  dog  mat  mouse  my  the
0    1    1    1      0   1    1
1    1    0    1      0   0    1
2    1    0    1      1   0    2
3    1    1    0      1   1    0

In [132]:
frequencies = vectors.toarray().sum(axis=0)

sorted_indices = frequencies.argsort()[::-1]
sorted_feature_names = [feature_names[idx] for idx in sorted_indices]
sorted_frequencies = frequencies[sorted_indices]


for i in range(len(sorted_feature_names)):
    print(sorted_feature_names[i], ": ", sorted_frequencies[i])

the :  4
cat :  4
mat :  3
my :  2
mouse :  2
dog :  2


In [133]:
from sklearn.feature_extraction.text import TfidfVectorizer 

tfidf_vectorizer = TfidfVectorizer(max_features=max_features)
tfidf_vectors = tfidf_vectorizer.fit_transform(documents)

print("\nTF-IDF Vectorization:")

feature_names=tfidf_vectorizer.get_feature_names_out()

example_df = pd.DataFrame(data=tfidf_vectors.toarray(),columns=feature_names)
example_df


TF-IDF Vectorization:


cat       dog       mat     mouse        my       the
0  0.341846  0.516470  0.418127  0.000000  0.516470  0.418127
1  0.500491  0.000000  0.612172  0.000000  0.000000  0.612172
2  0.304813  0.000000  0.372830  0.460519  0.000000  0.745660
3  0.356966  0.539313  0.000000  0.539313  0.539313  0.000000

In [134]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

corpus = df['processed_Message']


max_features = 100

count_vectorizer = CountVectorizer(max_features=max_features)

vectors = count_vectorizer.fit_transform(corpus)

tfidf_vectorizer = TfidfVectorizer(max_features=max_features)
tfidf_vectors = tfidf_vectorizer.fit_transform(corpus)

In [135]:
from sklearn.model_selection import train_test_split

X = vectors

y = df['Category']

X = X.toarray()

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [136]:
import numpy as np

# Ensure all values are converted to numeric, replacing non-numeric ones with NaN
X_train = np.array([[float(value) if str(value).replace('.', '', 1).isdigit() else np.nan for value in row] for row in X_train])

# Fill NaN values with 0 (or use another method)
X_train = np.nan_to_num(X_train)

# Ensure dtype is float
X_train = X_train.astype(np.float32)

In [137]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train = le.fit_transform(y_train)

In [140]:
y_pred_prob = model.predict(X_test)  # Ensure this outputs an array
y_pred = np.round(y_pred_prob).flatten()  # Ensure correct shape

44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [141]:
le = LabelEncoder()

# Encode original labels
y_test_encoded = le.fit_transform(y_test)  # 'true' -> 1, 'spam' -> 0

# Compute accuracy
accuracy = accuracy_score(y_test_encoded, y_pred)
print("Accuracy:", round(accuracy * 100, 2))

Accuracy: 96.27


In [142]:
from sklearn.metrics import accuracy_score
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=10, batch_size=32)

Epoch 1/10


C:\Users\user\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


131/131 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7239 - loss: 0.5676
Epoch 2/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9454 - loss: 0.1685
Epoch 3/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9606 - loss: 0.1144
Epoch 4/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9705 - loss: 0.0981
Epoch 5/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9708 - loss: 0.0885
Epoch 6/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9724 - loss: 0.0878
Epoch 7/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9733 - loss: 0.0842
Epoch 8/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9761 - loss: 0.0752
Epoch 9/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9800 - loss: 0.0655
Epoch 10/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9780 - loss: 0.0728


In [143]:
print(X_train.dtype)
print(y_train.dtype)

float32
int64


In [144]:
X_train = X_train.astype('float32')

In [145]:
import numpy as np

y_pred_prob = model.predict(X_test)
y_pred = np.round(y_pred_prob)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", round(accuracy*100,2))

44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Accuracy: 96.34


In [146]:
message="call to get free prize one million dollars"

processed_message=preprocess_text(message)

vector=tfidf_vectorizer.transform([processed_message])
vector_dense=vector.toarray()

y_pred_prob = model.predict(vector_dense)

y_pred = np.round(y_pred_prob)
print(y_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step
[[1.]]


In [147]:
message="hi bro call na at 11 pm "

processed_message=preprocess_text(message)

vector=tfidf_vectorizer.transform([processed_message])
vector_dense=vector.toarray()

y_pred_prob = model.predict(vector_dense)

y_pred = np.round(y_pred_prob)
print(y_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
[[0.]]


In [148]:
print(np.unique(y_train, return_counts=True))

(array([0, 1], dtype=int64), array([3618,  561], dtype=int64))


In [ ]:
# need double check to determine the spam and true message